//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OPCServerConfig.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_TRACE_TAB                   112
#define IDD_ServerAllowConf             113
#define IDD_SERVER_CONF                 114
#define IDD_UserToken                   115
#define IDD_CertificateStore            116
#define IDD_ThreadSettings              117
#define IDD_UAEndPoint_Security         118
#define IDR_POPUP_EDIT                  119
#define IDD_SERVER_AVAILABLITIES        119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_OPCServerConfigTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDC_COMBO_ENStckTrace           1000
#define IDC_COMBO_StckTraceLevel        1001
#define IDC_COMBO_EnSrvrAppTrcLevel     1002
#define IDC_COMBO_SrvrAppTrcLevel       1003
#define IDC_EDIT_MaxTraceEntries        1004
#define IDC_EDIT_MaxBackupFiles         1005
#define IDC_COMBO_AppTraceDisFlush      1006
#define IDC_BUTTON_XML                  1007
#define IDC_COMBO_TraceEvents           1008
#define IDC_COMBO_EnPubSubStckTrce      1009
#define IDC_EDIT_MaxTrstListSize        1010
#define IDC_COMBO_SendCertChain         1011
#define IDC_COMBO_GenerateCert          1018
#define IDC_EDIT_CommonName             1019
#define IDC_EDIT_DomainComponent        1020
#define IDC_EDIT_Organization           1021
#define IDC_EDIT_OrganizationUnit       1022
#define IDC_EDIT_LocationName           1023
#define IDC_EDIT_CountryLetterCode      1024
#define IDC_EDIT_ValidYears             1025
#define IDC_COMBO_CertKeyLngth          1027
#define IDC_COMBO_CertType              1028
#define IDC_EDIT_DNSName                1029
#define IDC_COMBO_AllowDeprSecPolcy     1031
#define IDC_EDIT_RejectedCertCount      1032
#define IDC_COMBO_ProvisionModeAct      1033
#define IDC_COMBO_DeactAftInitConf      1034
#define IDC_EDIT_MaxReqAge              1035
#define IDC_EDIT_MaxSessCount           1036
#define IDC_EDIT_MaxSessPerCli          1037
#define IDC_EDIT_MinSessTimeout         1038
#define IDC_EDIT_MaxSessTimeout         1039
#define IDC_EDIT_MaxBrowContPoints      1040
#define IDC_EDIT_MaxBrowsRes            1041
#define IDC_EDIT_MaxNodesBrowse         1042
#define IDC_EDIT_MaxNodePTBrowPath      1043
#define IDC_EDIT_MaxNumNodesPHistRD     1044
#define IDC_EDIT_MaxNodePHistREvnts     1045
#define IDC_EDIT_MaxNdPHistUpdData      1046
#define IDC_EDIT_MaxNdPHistUpdEvnts     1047
#define IDC_EDIT_MaxHistContPoints      1048
#define IDC_EDIT_MinPublishInterval     1055
#define IDC_EDIT_MaxPublishInterval     1056
#define IDC_MFCEDITBROWSE_SrvrCert      1056
#define IDC_EDIT_MaxKeepAliveInterval   1057
#define IDC_MFCEDITBROWSE_SrvrPrvtKey   1057
#define IDC_EDIT_MinKeepAliveInterval   1057
#define IDC_EDIT_MinSubsLifeTime        1058
#define IDC_MFCEDITBROWSE_CertTrustList 1058
#define IDC_MFCEDITBROWSE_TraceFile     1059
#define IDC_EDIT_MaxSubsLifeTime        1059
#define IDC_MFCEDITBROWSE_CertRvctnList 1059
#define IDC_MFCEDITBROWSE_RejectedCert  1060
#define IDC_EDIT_MaxRetransQueSize      1060
#define IDC_EDIT_MaxNotfctionPPublsh    1061
#define IDC_MFCEDITBROWSE_DrbleSubs     1061
#define IDC_MFCEDITBROWSE_IssuerCert    1061
#define IDC_EDIT_MaxDataQueueSize       1062
#define IDC_MFCEDITBROWSE_IssuerRevocList 1062
#define IDC_EDIT_MaxEventQueSize        1063
#define IDC_MFCEDITBROWSE_CertTrustLst  1063
#define IDC_EDIT_MaxSubsCount           1064
#define IDC_MFCEDITBROWSE_CertRevocList 1064
#define IDC_EDIT_MaxSubsPSess           1065
#define IDC_MFCEDITBROWSE_RjctedUsrCert 1065
#define IDC_MFCEDITBROWSE_IssuerRvctnList 1065
#define IDC_EDIT_MaxMontrdItemCnt       1066
#define IDC_LIST_SampleRates            1066
#define IDC_EDIT_MaxMntrdItmPSubsCnt    1067
#define IDC_BUTTON_InsertSR             1067
#define IDC_EDIT_MaxMntrdItmPSessCnt    1068
#define IDC_BUTTON_DeleteSR             1068
#define IDC_EDIT_MaxSuppSmpleRate       1069
#define IDC_EDIT_MinSuppSmpleRate       1069
#define IDC_LIST_Local_Ids              1069
#define IDC_COMBO_DrbleSubsSuppEn       1070
#define IDC_BUTTON_InsertLocalIds       1070
#define IDC_BUTTON_DeleteLIds           1071
#define IDC_EDIT_MaxMonitItmQueSize     1072
#define IDC_EDIT_InsrtSmplngRate        1072
#define IDC_EDIT_LiveQueSize            1073
#define IDC_EDIT_InsrtSrvrPrfiles       1073
#define IDC_LIST_ServerProfiles         1074
#define IDC_BUTTON_InsertSP             1075
#define IDC_BUTTON_DeleteSP             1076
#define IDC_LIST_ServerCaps             1077
#define IDC_BUTTON_InsertSCaps          1078
#define IDC_BUTTON_DeleteSC             1079
#define IDC_BUTTON_UpdateSR             1080
#define IDC_BUTTON_UpdateLocalIds       1081
#define IDC_BUTTON_UpdateSP             1082
#define IDC_COMBO_AvailblSmplngRates    1083
#define IDC_BUTTON_UpdateSCaps          1083
#define IDC_COMBO_AvailbleLocalIds      1084
#define IDC_COMBO_AvailbleSrvrPrfiles   1085
#define IDC_COMBO_ServerCapablties      1086
#define IDC_COMBO_AudioActivated        1087
#define IDC_EDIT_MinSizeTransctionMan   1089
#define IDC_EDIT_MaxSizeTransctionMan   1090
#define IDC_EDIT_MinSizeSubsMan         1091
#define IDC_EDIT_MaxSizeSubsMan         1092
#define IDC_EDIT_ProductUri             1093
#define IDC_EDIT_ManfcturerName         1094
#define IDC_EDIT_InsrtLocalId           1094
#define IDC_EDIT_InsertSCaps            1095
#define IDC_EDIT_ProductName            1097
#define IDC_EDIT_SoftwareVersion        1098
#define IDC_EDIT_BuildNumber            1099
#define IDC_EDIT_ServerUri              1100
#define IDC_EDIT_ServerName             1101
#define IDC_COMBO_EnAnnymsLogin         1102
#define IDC_COMBO_EnUserPassLog         1103
#define IDC_COMBO_EnCert                1104
#define IDC_EDIT_SecPolicy              1105
#define IDC_EDIT_MaxRjctedUserCertCnt   1111
#define IDC_COMBO_AutoCertExchnge       1112
#define IDC_EDIT_DiscSrvrStoreName      1113
#define IDC_EDIT_DiscSrvrCertName       1114
#define IDC_EDIT_RegistrationInterval   1115
#define IDC_EDIT_MaxArrayLngth          1117
#define IDC_EDIT_MaxMsgSize             1118
#define IDC_COMBO_EnStckThreadPool      1121
#define IDC_COMBO_BlockOnAdd            1123
#define IDC_COMBO_RdndncySupp           1125
#define IDC_EDIT_SerializerType         1126
#define IDC_EDIT_URL                    1127
#define IDC_COMBO_DisUserTokenPolicyChck 1137
#define IDC_COMBO_DisCertSignAlgCheck   1138
#define IDC_COMBO_DisCertUsageCheck     1139
#define IDC_EDIT_SecPolicy3             1148
#define IDC_EDIT_MsgScrtyMode5          1149
#define IDC_EDIT_MsgScrtyMode6          1150
#define IDC_EDIT_MaxMemoryAlloc         1152
#define IDC_EDIT_MaxStrngLngth          1153
#define IDC_EDIT_MaxByteStrngLngth      1154
#define IDC_EDIT_MinThreads             1155
#define IDC_EDIT_MaxThreads             1156
#define IDC_EDIT_MaxJobs                1157
#define IDC_EDIT_Timeout                1158
#define IDC_COMBO_IsVisible             1160
#define IDC_COMBO_IsDiscUrl             1161
#define IDC_COMBO_AutoTrstAllClientCert 1162
#define IDC_COMBO_CreateSgnChain        1163
#define IDC_COMBO_DisErrCertTimeInvld   1164
#define IDC_COMBO_DisErrCertIssTimeInvld 1165
#define IDC_COMBO_DisNonceLngthChck     1166
#define IDC_COMBO_DisErrCertRvctnUnknwn 1167
#define IDC_COMBO_DisErrCertIssRvctnUnknwn 1168
#define IDC_COMBO_DisErrCertKeyShort    1169
#define IDC_COMBO_DisErrCertKeyLong     1170
#define IDC_COMBO_DisAppUriCheck        1171
#define IDC_EDIT__MsgScrtyMode4         1173
#define IDC_EDIT_MsgSecMode             1174
#define IDC_EDIT_MsgScrtyMode           1175
#define IDC_EDIT__MsgScrtyMode2         1176
#define IDC_EDIT_SecPolicy2             1177
#define IDC_EDIT_SecurityPolicy         1178
#define IDC_EDIT_HostName               1179
#define IDC_EDIT_Geometry               1180
#define IDC_EDIT_MsgScrtyMode3          1181

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
